# Generated by Django 4.0.2 on 2022-02-24 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_alter_course_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('teaching_course', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
    ]
