# Generated by Django 4.0.2 on 2022-03-03 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200)),
                ('client_phone_number', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='news',
            old_name='tarif',
            new_name='description',
        ),
    ]
