# Generated by Django 4.0.2 on 2022-03-10 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_application_rename_tarif_news_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='client_last_name',
            field=models.CharField(max_length=200, null=True, verbose_name='Clint last name'),
        ),
        migrations.AddField(
            model_name='application',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.course'),
        ),
    ]
